

<MenuWidget>:
    canvas.before:
        Color:
            rgba: 0, 0, 0, 0.8
        Rectangle:
            size: self.size
    Label:
        text: root.parent.menu_title
        pos_hint: { "center_x": 0.5, "center_y": 0.6}
    Button:
        text: root.parent.menu_button_title
        pos_hint: { "center_x": 0.5, "center_y": 0.4}
        size_hint : 0.2, 0.1
        on_press: root.parent.on_menu_button()